sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: Deploy
      name: "deploy to dev"
      if: env(deploy_to) IS blank
      script: echo "dev"
    - stage: Deploy
      name: "deploy to qa"
      if: env(deploy_to)=qa
      script: echo $ENV
