sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: deploy
      name: "deploy to dev"
      deploy:
        env:
          - ENV=DEV
        script: echo $ENV
    - stage: deploy
      name: "deploy to qa"
      deploy:
        on:
          condition: $TEST=true
        env:
          - ENV=QA
        script: echo $ENV
