sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: deploytodev
      name: "deploy to dev"
      deploytodev:
        env: ENV=DEV
        script: echo $ENV
    - stage: deploytoqa
      name: "deploy to qa"
      deploytoqa:
        on:
          condition: env(TEST)=true
        env: ENV=QA
        script: echo $ENV
