sudo: true

env:
  global:
  - ENV=dev

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: deploy
      name: "deploy to dev"
      env:
        - ENV=QA
      script: ./deploy.sh
    - stage: deploy
      on:
        condition: $TEST=true
      name: "deploy to qa"
      env:
        - ENV=QA
      script: ./deploy.sh
