sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      name: "unit test"
      script: echo "testing..."
    - stage: Test
      name: "integration test"
      script: echo "testing..."      
    - stage: Deploy
      name: "deploy to dev"
      script: echo "dev"
    - stage: Deploy
      name: "deploy to qa"
      script: echo $ENV
