sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: Deploy
      name: "deploy to dev"
      env: ENV=DEV
      script: echo $ENV
    - stage: Deploy
      name: "deploy to qa"
      if: env(deploy_env)=QA
      env: ENV=QA
      script: echo $ENV
