sudo: true

language: java

stages:
  - Test
  - name: Deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: Test
      script: echo "testing..."
    - stage: Deploy
      name: "deploy to dev"
      if: env(ENV) IS blank
      script: echo $ENV
    - stage: Deploy
      name: "deploy to qa"
      if: env(ENV)=QA
      script: echo $ENV
